# Generated by Django 3.1 on 2020-08-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(default='0000000', editable=False, max_length=7),
        ),
    ]
