# Generated by Django 3.1 on 2020-08-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='p_name',
            field=models.CharField(default='proucts', max_length=7),
        ),
    ]
